spring:
  application:
    name: talentadmin
  security:
    user:
      name: "admin"
      password: "123456"
  mail:
    host: smtp.qq.com
    username: 984550199@qq.com
    password: lihqaphmgbfjbcii
  boot:
    admin:
      notify:
        mail:
          to: javaweb@vbooster.cn
          from: 984550199@qq.com
server:
  port: 8769
eureka:
  client:
    leaseRenewalIntervalInSeconds: 5
    service-url:
      defaultZone:  ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}

ribbon:
  ReadTimeout: 10000
  ConnectTimeout : 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

management:
  server:
    servlet:
      context-path: /monitor
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true
    info:
      enabled: true