spring:
  application:
    name: talentadmin
  security:
    user:
      name: "admin"
      password: "admin"
server:
  port: 8769
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka